// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhNc7qCASrWkurcqCAadh9sdfzEe-jhY',
    appId: '1:566312450956:web:3aa7e1c840810d744ff4a9',
    messagingSenderId: '566312450956',
    projectId: 'tailor-7b7cb',
    authDomain: 'tailor-7b7cb.firebaseapp.com',
    storageBucket: 'tailor-7b7cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ATZkB3osyDL3zy0SV7-Amp8__YRfED8',
    appId: '1:566312450956:android:8e95d70988acc9904ff4a9',
    messagingSenderId: '566312450956',
    projectId: 'tailor-7b7cb',
    storageBucket: 'tailor-7b7cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9pSJR1HFWvuVegs6N30zmKcbImRUHOfc',
    appId: '1:566312450956:ios:010c99cad8deb0d34ff4a9',
    messagingSenderId: '566312450956',
    projectId: 'tailor-7b7cb',
    storageBucket: 'tailor-7b7cb.firebasestorage.app',
    iosClientId:
        '566312450956-mq8fnvjnlcjklrc1np0cjhsdtt6nl7rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9pSJR1HFWvuVegs6N30zmKcbImRUHOfc',
    appId: '1:566312450956:ios:010c99cad8deb0d34ff4a9',
    messagingSenderId: '566312450956',
    projectId: 'tailor-7b7cb',
    storageBucket: 'tailor-7b7cb.firebasestorage.app',
    iosClientId:
        '566312450956-mq8fnvjnlcjklrc1np0cjhsdtt6nl7rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNhNc7qCASrWkurcqCAadh9sdfzEe-jhY',
    appId: '1:566312450956:web:2e08e5b801327b1b4ff4a9',
    messagingSenderId: '566312450956',
    projectId: 'tailor-7b7cb',
    authDomain: 'tailor-7b7cb.firebaseapp.com',
    storageBucket: 'tailor-7b7cb.firebasestorage.app',
  );
}
